name: Fast DDS Python Windows CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  # python main - fastdds master
  nightly-windows-ci-main:
    strategy:
      fail-fast: false
      matrix:
        os-version:
          - 'windows-2019'
        vs-toolset:
          - 'v142'
        fastdds-python-branch:
          - 'main'
        fastdds-branch:
          - 'master'
    uses: eProsima/Fast-DDS-Python/.github/workflows/reusable-windows-ci.yml@main
    with:
      os-version: ${{ matrix.os-version }}
      vs.toolset: ${{ matrix.vs-toolset }}
      label: 'nightly-${{ matrix.os-version }}-${{ matrix.vs-toolset }}-ci-${{ matrix.fastdds-python-branch }}'
      fastdds-python-branch: ${{ matrix.fastdds-python-branch }}
      fastdds-branch: ${{ matrix.fastdds-branch }}
      run-build: true
      run-tests: true

  # python 1.4.x - fastdds 2.14.x/2.13.x
  nightly-windows-ci-1_4_x:
    strategy:
      fail-fast: false
      matrix:
        os-version:
            - image: 'windows-2019'
              vs-toolset: 'v142'
            - image: 'windows-2017'
              vs-toolset: 'v141'
        fastdds-python-branch:
          - '1.4.x'
        fastdds-branch:
          - '2.14.x'
          - '2.13.x'
    uses: eProsima/Fast-DDS-Python/.github/workflows/reusable-windows-ci.yml@1.4.x
    with:
      os-version: ${{ matrix.os-version.image }}
      vs.toolset: ${{ matrix.os-version.vs-toolset }}
      label: 'nightly-${{ matrix.os-version.image }}-${{ matrix.os-version.vs-toolset }}-ci-${{ matrix.fastdds-python-branch }}-${{ matrix.fastdds-branch }}'
      fastdds-python-branch: ${{ matrix.fastdds-python-branch }}
      fastdds-branch: ${{ matrix.fastdds-branch }}
      run-build: true
      run-tests: true

  # python 1.2.x - fastdds 2.10.x
  nightly-windows-ci-1_2_x:
    strategy:
      fail-fast: false
      matrix:
        os-version:
            - image: 'windows-2019'
              vs-toolset: 'v142'
            - image: 'windows-2017'
              vs-toolset: 'v141'
        fastdds-python-branch:
          - '1.2.x'
        fastdds-branch:
          - '2.10.x'
    uses: eProsima/Fast-DDS-Python/.github/workflows/reusable-windows-ci.yml@1.2.x
    with:
      os-version: ${{ matrix.os-version.image }}
      vs.toolset: ${{ matrix.os-version.vs-toolset }}
      label: 'nightly-${{ matrix.os-version.image }}-${{ matrix.os-version.vs-toolset }}-ci-${{ matrix.fastdds-python-branch }}'
      fastdds-python-branch: ${{ matrix.fastdds-python-branch }}
      fastdds-branch: ${{ matrix.fastdds-branch }}
      run-build: true
      run-tests: true

  # python 1.0.x - fastdds 2.6.x
  nightly-windows-ci-1_0_x:
    strategy:
      fail-fast: false
      matrix:
        os-version:
            - image: 'windows-2019'
              vs-toolset: 'v142'
            - image: 'windows-2017'
              vs-toolset: 'v141'
        fastdds-python-branch:
          - '1.0.x'
        fastdds-branch:
          - '2.6.x'
    uses: eProsima/Fast-DDS-Python/.github/workflows/reusable-windows-ci.yml@1.0.x
    with:
      os-version: ${{ matrix.os-version.image }}
      vs.toolset: ${{ matrix.os-version.vs-toolset }}
      label: 'nightly-${{ matrix.os-version.image }}-${{ matrix.os-version.vs-toolset }}-ci-${{ matrix.fastdds-python-branch }}'
      fastdds-python-branch: ${{ matrix.fastdds-python-branch }}
      fastdds-branch: ${{ matrix.fastdds-branch }}
      run-build: true
      run-tests: false
